/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: facerate (https://sketchfab.com/facerate)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/elven-ranger-statue-71aec2d9f7724ae09992435ce8ff7258
title: Elven ranger statue
*/

import React, { useRef, useMemo} from 'react'
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model({ ...props }) {
  const group = useRef()
  const material = useMemo(() => {
    return new THREE.MeshStandardMaterial({ color: new THREE.Color('#2a2a2a'), roughness: 0.5, metalness: 0.9 })
  }, [])
  const { nodes } = useGLTF('/scene.glb')
  useFrame(() => (group.current.rotation.y += 0.004))

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={material} receiveShadow castShadow />
        <mesh geometry={nodes.mesh_1.geometry} material={material} receiveShadow castShadow />
        <mesh geometry={nodes.mesh_2.geometry} material={material} receiveShadow castShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
